# Java Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.37-beta

## Mod Properties
mod_id=rovi
mod_name=Rovi
mod_license=All Rights Reserved
mod_version=1.263.0.0
mod_group_id=iso2t.rovi

# Integrations
lombok_version=1.18.48
easyconfig_version=1.263.0.9